In [0]:
import torch
from __future__ import print_function
import numpy as np

In [23]:
empty_arr=torch.empty(5, 3)         #create empty array
print(empty_arr)

tensor([[2.9336e-36, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.0490e-08, 2.0568e+20, 5.3193e+22],
        [2.6705e-06, 1.3283e-08, 2.6194e+20],
        [1.7661e-04, 1.7154e-07, 1.5868e+00]])


In [24]:
rand_arr=torch.rand(5, 3)    #create random array
print(rand_arr)

tensor([[0.0729, 0.3181, 0.6642],
        [0.2351, 0.0892, 0.8377],
        [0.2408, 0.3181, 0.0664],
        [0.3808, 0.9036, 0.2080],
        [0.7571, 0.9954, 0.7884]])


In [25]:
zeros_arr=torch.zeros(5, 3, dtype=torch.long)   #create zero array
print(zeros_arr)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [26]:
self_arr=torch.tensor([5, 556.86])    #create self defined array
print(self_arr)

tensor([  5.0000, 556.8600])


In [27]:
x=self_arr.new_ones(5, 3, dtype=torch.int)
print(x)
print('size of x: ', x.size())

y=torch.randn_like(x, dtype=torch.float)
print(y)
print('size of y: ', y.size())

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
size of x:  torch.Size([5, 3])
tensor([[-0.6215, -0.1806,  0.3010],
        [ 0.4347,  2.0451,  0.7835],
        [ 0.9298, -0.9815,  2.2620],
        [ 1.6019, -0.6115,  0.2755],
        [ 1.0800, -1.1046,  0.2267]])
size of y:  torch.Size([5, 3])


In [28]:
a=torch.ones(5, 3, dtype=torch.float)
print(a)
b=torch.rand(5, 3)
print(b)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.9751, 0.8406, 0.0704],
        [0.9032, 0.6916, 0.1888],
        [0.3924, 0.3819, 0.9538],
        [0.0303, 0.1838, 0.3021],
        [0.4821, 0.3588, 0.3025]])


In [29]:
#operations on arrays
#different ways for addition
c=a+b
print(c)
d=torch.add(a, b)
print(d)
e=torch.empty(5, 3)
torch.add(a, b, out=e)
print(e)
b.add_(a)
print(b)

tensor([[1.9751, 1.8406, 1.0704],
        [1.9032, 1.6916, 1.1888],
        [1.3924, 1.3819, 1.9538],
        [1.0303, 1.1838, 1.3021],
        [1.4821, 1.3588, 1.3025]])
tensor([[1.9751, 1.8406, 1.0704],
        [1.9032, 1.6916, 1.1888],
        [1.3924, 1.3819, 1.9538],
        [1.0303, 1.1838, 1.3021],
        [1.4821, 1.3588, 1.3025]])
tensor([[1.9751, 1.8406, 1.0704],
        [1.9032, 1.6916, 1.1888],
        [1.3924, 1.3819, 1.9538],
        [1.0303, 1.1838, 1.3021],
        [1.4821, 1.3588, 1.3025]])
tensor([[1.9751, 1.8406, 1.0704],
        [1.9032, 1.6916, 1.1888],
        [1.3924, 1.3819, 1.9538],
        [1.0303, 1.1838, 1.3021],
        [1.4821, 1.3588, 1.3025]])


In [30]:
#accessing array like in numpy
print(b[:, 2])

tensor([1.0704, 1.1888, 1.9538, 1.3021, 1.3025])


In [31]:
#resizing arrays
f=torch.rand(4, 5)
g=f.view(20)
h=f.view(10, 2)
print(f.size(), g.size(), h.size())

torch.Size([4, 5]) torch.Size([20]) torch.Size([10, 2])


In [32]:
#to get python no. from tensor value
i=torch.rand(1)
print(i)
print(i.item())

tensor([0.1513])
0.15131759643554688


In [33]:
# NumPy Bridge : Converting from tensor to NumPy and vice versa

torch_arr_1=torch.ones(5, 3)
numpy_arr_1=torch_arr_1.numpy()
print(torch_arr_1)
print(numpy_arr_1)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [34]:
#IMOPRTANT THING HERE
one_arr=torch.ones(5, 3)
torch_arr_1.add_(one_arr)
#here changing torch arr also changes the numpy arr also ***************************
print(torch_arr_1)
print(numpy_arr_1)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [37]:
#from numpy to torch array
np_arr=np.ones((5, 3))
torch_arr=torch.from_numpy(np_arr)
np.add(np_arr, np.ones((5, 3)), out=np_arr)
print(np_arr)
print(torch_arr)


[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]], dtype=torch.float64)


In [0]:
#CUDA Tensors
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!