In [0]:
import torch

In [10]:
#AUTOGRAD
x=torch.ones(5, 3, requires_grad=True)
print(x)
print(x.grad_fn)
y=x+2
print(y)
print(y.grad_fn)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)
None
tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]], grad_fn=<AddBackward0>)


In [11]:
z=y*y*5
print(z)
out=z.mean()  #calculates the avg of all elements
print(out)

tensor([[45., 45., 45.],
        [45., 45., 45.],
        [45., 45., 45.],
        [45., 45., 45.],
        [45., 45., 45.]], grad_fn=<MulBackward0>)
tensor(45., grad_fn=<MeanBackward0>)


In [12]:
# changing required grad status
a=torch.rand(5, 3)
a=((a*8)/(a-5))
print(a)
print(a.requires_grad)
a.requires_grad=True
print(a.requires_grad)
b=(a*a).sum()
print(b)
print(b.grad_fn)

tensor([[-0.9991, -0.4924, -0.9523],
        [-1.0088, -0.5040, -1.3087],
        [-1.1777, -1.3081, -1.4205],
        [-0.3984, -1.0066, -1.4239],
        [-0.7099, -0.4427, -1.0482]])
False
True
tensor(15.2459, grad_fn=<SumBackward0>)


In [13]:
#getting grads
out.backward()
print(x.grad)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


In [24]:
#VECTOR-JACOBIAN
x=torch.randn(3, requires_grad=True)
print('x:', x)
y=x*2
while y.data.norm() < 1000:                        #return L2 norm of the array
  y=y*5
  print(y)

 



x: tensor([-0.9136, -1.8082, -1.6919], requires_grad=True)
tensor([ -9.1359, -18.0825, -16.9191], grad_fn=<MulBackward0>)
tensor([-45.6796, -90.4123, -84.5955], grad_fn=<MulBackward0>)
tensor([-228.3981, -452.0615, -422.9774], grad_fn=<MulBackward0>)
tensor([-1141.9907, -2260.3074, -2114.8867], grad_fn=<MulBackward0>)


In [25]:
#calculating vector jacobian product

v=torch.tensor([0.02, 5.67, 8.00], dtype=torch.float)

y.backward(v, retain_graph=True)

print(x.grad)


tensor([   25.0000,  7087.5000, 10000.0000])


In [26]:
#stopping autograd.

print(x.requires_grad)
print((x**2).requires_grad)

with torch.no_grad():
  print((x**2).requires_grad)

True
True
False


In [29]:
print(x.requires_grad)
y=x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)
